FlowPanelApp/Controllers/SchoolController.cs
using FlowPanelApp.Models;
using FlowPanelApp.Services.SchoolService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using static System.Net.Mime.MediaTypeNames;

namespace FlowPanelApp.Controllers
{
    public class SchoolController : Controller
    {
        private readonly ISchoolService _schoolService;

        public SchoolController(ISchoolService schoolService)
        {
            _schoolService = schoolService;
        }
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var model = await _schoolService.GetAll();    
            foreach (var item in model)
            {
                if(item.Logo == null)
                {
                    item.Logo = new byte[0];
                }
            }
            return View(model);
        }

        [Authorize]
        public IActionResult CreateSchool()
        {
            return View();
        }
        public async Task<IActionResult> Create(School school, IFormFile file)
        {
            try
            {
                if (file != null && file.Length > 0)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        file.CopyTo(memoryStream);
                        byte[] bytes = memoryStream.ToArray();

                        school.Logo = bytes;
                    }
                }
                await _schoolService.CreateSchool(school);
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ViewBag.Message = ex.Message;
                return RedirectToAction("Index");
            }        
        }
        [Authorize]
        public IActionResult EditSchool(long SchoolId)
        {
            var model = _schoolService.GetSchoolById(SchoolId);
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateSchool(School school, IFormFile file)
        {
            try
            {
                if (file != null && file.Length > 0)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        file.CopyTo(memoryStream);
                        byte[] bytes = memoryStream.ToArray();

                        school.Logo = bytes;
                    }
                }
                else
                {
                    school.Logo = await _schoolService.GetSchoolLogoBySchoolId(school.SchoolId);
                }
                await _schoolService.UpdateSchool(school);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return RedirectToAction("Index");
            }
        }

        public IActionResult SchoolDetails(long schoolId)
        {
            return RedirectToAction("Index", "Classes", new {schoolID = schoolId});
        }
    }
}

FlowPanelApp/Controllers/UserController.cs
using FlowPanelApp.Models;
using FlowPanelApp.Services.UserService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace FlowPanelApp.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;       
        public UserController(IUserService userService)
        {
            _userService = userService;                 
        }
        [Authorize]
        public async Task<IActionResult> Index()
        {
            if (HttpContext.User.Identities.Select(x => x.RoleClaimType == "Admin").FirstOrDefault())
            {
                var model = await _userService.GetAll();
                return View(model);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
        [Authorize]
        public IActionResult CreateUser()
        {
            if (HttpContext.User.Identities.Select(x => x.RoleClaimType == "Admin").FirstOrDefault())
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
        [Authorize]
        public async Task<IActionResult> Create(User user)
        {
            if (HttpContext.User.Identities.Select(x => x.RoleClaimType == "Admin").FirstOrDefault())
            {
                await _userService.AddUser(user);
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
        [Authorize]
        public async Task<IActionResult> Delete(long userId)
        {
            if (HttpContext.User.Identities.Select(x => x.RoleClaimType == "Admin").FirstOrDefault())
            {
                var user = await _userService.GetUserById(userId);
                await _userService.DeleteUser(user);
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
        [Authorize]
        public async Task<IActionResult> EditUser(long userId)
        {
            if (HttpContext.User.Identities.Select(x => x.RoleClaimType == "Admin").FirstOrDefault())
            {
                var model = await _userService.GetUserById(userId);
                return View(model);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
        [Authorize]
        public async Task<IActionResult> Edit(User user)
        {
            if (HttpContext.User.Identities.Select(x => x.RoleClaimType == "Admin").FirstOrDefault())
            {
                await _userService.EditUser(user);
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

FlowPanelApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Panel elektronicznego dziennika</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">E-Panel</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Ogłoszenia</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Informacje</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="School" asp-action="Index">Szkoły</a>
                        </li>
                        @if(@User.Identities.Select(x => x.RoleClaimType).FirstOrDefault() == "Admin")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Użytkownicy</a>
                            </li>
                        }                     
                    </ul>
                </div>
                <div style="margin-bottom: 10px;">
                    <p>
                        <a asp-action="Logout" asp-controller="Login">
                            <div class="float-right" style="padding-bottom: 5px;">
                                <input type="button" class="btn btn-secondary" value="Wyloguj" />
                            </div>
                        </a>
                    </p>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FlowPanelApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>